### PR TITLE
Add all missing stdlib.h and errlog.h includes

### PR DESCRIPTION
**Pull request by hdante**

### CODE REVIEW

**Comment by rsluiter** [comment]
Hello Henrique,

Correct me if I am wrong, the purpose of your pull request appears to be to make header files that are already included implicitly, explicit.  For example, the source file devESP300.cc includes errlog.h implicitly via the following (:## indicates the file line number);
devESP300.cc:44->motordevCom.h:35->motordrvCom.h:52->epicsMessageQueue.h:31->locationException.h:23->errlog.h
At each of the above line numbers, you will find a "#include" for the file to the right of "->".

We have no coding practices in EPICS, but I have always assumed that when a header file requires definitions from another header file, that it will explicitly include that header file, so I don't have to in my source file.

You may wonder how I obtained the above chain of header files? A procedure follows;

1) delete the object file for the source file of interest; e.g. NewportSrc/O.vxWorks-ppc32-debug/devESP300.o
2) rebuild the object file (i.e., run "make") to get the compiler command line. Copy&paste the command line into an editor.
3) From the editor, replace "-c" with "-E" in the compiler command line.
4) From the editor, append " > devESP300.i" to the end of the compiler command line.
5) Save compiler command line to a file named "build" in the object directory of interest; in this case, O.vxWorks-ppc32-debug.
6) cd to the object directory of interest and make "build" executable; i.e., chmod a+x build
7) With VxWorks I have to setup my environment variables, with Linux this is not necessary.
8) Execute "build" and you should get a *.i file; e.g., devESP300.i

The two attached files were built from the github HEAD and your pull request.

[HEADdevESP300.i.txt](https://github.com/epics-modules/motor/files/411972/HEADdevESP300.i.txt)
[PULLdevESP300.i.txt](https://github.com/epics-modules/motor/files/411973/PULLdevESP300.i.txt)

Let me know if you have any questions,
Ron

**Comment by MarkRivers** [comment]
Ron,
I think the proposed changes are correct.  My understanding is that if your C code directly uses functions defined in errlog.h you should #include <errlog.h>.  Relying on another include file to include errlog.h is dangerous.  In the case you cite above what if locationException.h were re-implemented so it no longer needed errlog.h?  Your code would now fail to compile.

**Comment by MarkRivers** [comment]
My comment had a special character that caused missing text.  It should read

if your C code directly uses functions defined in errlog.h you should include the line:
#include \<errlog.h\>

**Comment by rsluiter** [comment]
Mark,
If the criteria is that all direct references in source code to objects defined in header files needs an explicit #include, then there is a lot of work to do without much payback. I chose devESP300.cc because there is not much there, but even this file has references to sprintf with no explicit #include <stdio.h>. A close look at EPICS source code would show similar results; everything needs stlib.h, stdio.h, epicsTypes.h, math.h, etc., etc.. But since other header files include these, I don't have to... until one of those header files is changed, and then I do. But the need for that change will be obvious. Until then I would prefer to spend time on something that is actually broken.

**Comment by hdante** [comment]
Ron, this patch fixes compilation with epics base 3.16 HEAD branch. EPICS motor will not compile without this.

**Comment by MarkRivers** [comment]
My point exactly!  That is why it is a bad idea to rely some other include file doing the work for you.  Things change in EPICS base and now 62 files needed to be edited.

**Comment by rsluiter** [comment]
Hello Henrique,
"EPICS motor will not compile without this." That is a relevant piece of information that you could have shared when you made the pull request. I will confirm your results before merging the pull request.

**Comment by kmpeters** [comment]
@hdante,

Which OS and EPICS_HOST_ARCH are you using for your builds?

**Comment by hdante** [comment]
linux-x86_64 (Red Hat 6)

**Comment by rsluiter** [comment]
Hello Henrique,

I am unable to duplicate your results. I have built the "master" branch of the motor module against the "master" branch of the asyn module and base-3.16.0.1 under two configurations;
- RHEL6 using gcc 4.4.7 
- RHEL7 using gcc 4.8.5 
What compiler are you using?

**Comment by hdante** [comment]
I'm using RHEL 6.6 with gcc 4.4.7. I believe base 3.16.0.1 compiles without the patches, though. The problem appears in EPICS base master branch. Here's the commit I've used:

935ab02bc1ae6f99dc5aed60fe15fe9b681d4e69 Fix build failure on Solaris

or

998c3c1648629aba6debfc3c5178eac083aac7e2 Clean up warnings from gcc 5.2

https://github.com/epics-base/epics-base/commit/935ab02bc1ae6f99dc5aed60fe15fe9b681d4e69

**Comment by rsluiter** [comment]
Hello Henrique,
I see that the compiler errors are a consequence of [this change](https://github.com/epics-base/epics-base/commit/64c1a28f69a2f6d2f7d021c68b91f69fb6a2ccdc) to the EPICSbase 3.16 branch that removed "unused locationException.h includes" from epicsMessageQueue.h.

I will merge your pull request.

Thanks for helping keep the motor module up to date,
Ron

**Pull request merged**
