### PR TITLE
200317 no defs in release

### PR DESCRIPTION
**Pull request by tboegi**

### CODE REVIEW

**Comment by kmpeters** [comment]
The dummy definitions were added because empty definitions caused other problem.  I'm reluctant to comment them out, since they are required.

**Comment by tboegi** [comment]
I don't know which problems the dummy definitions cause -
so I'll close the PR

**Comment by ralphlange** [comment]
Setting SUPPORT is a valid way to avoid repeating the support location over and over again in manually managed RELEASE files.

When used in combination with an included `RELEASE.local` file that contains generated full paths (like when using the ci-scripts module), a `SUPPORT=/foo/bar` definition will not be overwritten by the generated settings.
To the test in Base, `SUPPORT=/foo/bar` looks like another definition of a dependency module. If a different module in the build happens to specify `SUPPORT=/bar/foo`, the test will bark, even if both definitions are not used.

Module definitions are sometimes used to activate specific parts of Makefiles that are only needed when that dependency module is defined. (Frequently used for dependencies that are not mandatory.) In such cases, not defining a module may have unwanted side effects.

**Comment by ralphlange** [comment]
Starting with commit epics-base/ci-scripts@aee11f266bb2a8d845d6f70c198e537060a120cf, the ci-scripts modules overwrites the RELEASE file in dependency modules, which should get rid of the issue.

**Pull request closed without merging**
