### PR TITLE
Add missing dependency on motorRecord.h

### PR DESCRIPTION
**Pull request by NickeZ**

### CODE REVIEW

**Comment by rsluiter** [comment]
Hello Niklas,
 Is there something in motordevCom.h that requires motorRecord.h?

**Comment by NickeZ** [comment]
Isn't "struct motorRecord *" defined in motorRecord.h?

**Comment by anjohnson** [comment]
It is often sufficient and may be preferable in some circumstances to declare (without defining) a struct as long as all the compiler needs to know is that the type exists (so pointers to it can be created). The compiler can pass a pointer to a struct around without having to know the detail of what is being pointed to, and pulling in a definition when the code doesn't need it is going to slow down compilation unnecessarily. If there is no need to include the full `motorRecord.h` header I recommend not doing so.

**Comment by rsluiter** [comment]
Not to under cut Andrew's comment or discourage you from making pull request, but if I were confident there would be no unintended consequences of your pull request, I would suggest that you make your pull request more comprehensive and eliminate, what would be, the duplicate "#include motorRecord"s that would exist in the nearly 40 "device" level files (e.g., https://github.com/rsluiter/motor/blob/master/motorApp/KohzuSrc/devSC800.cc) as a result of your suggested change.

As the motor module, and more specifically, the Model 1 motor record device/driver support currently stands (which is what your pull request would effect), I am not inclined to change all those files for what appears to be coding style. If you are having compiler or run-time errors associated with the existing motordevCom.h, we could discuss that offline (sluiter@aps.anl.gov).

**Comment by NickeZ** [comment]
Yeah, the compiler complained and I thought it was best practice to always include all used headers. It was simply very easy to do a drive-by patch thanks to github, but feel free to close this.

I now realize that you have other best practices for EPICS/motorRecord.

**Comment by NickeZ** [comment]
Yeah, the compiler complained and I thought it was best practice to always
include all needed types. It was simply very easy to do a drive-by patch
thanks to github, but feel free to close this.

**Pull request closed without merging**
