### PR TITLE
Fix for stale or soon to be stale RBV values during motor record initialization

### PR DESCRIPTION
**Pull request by kmpeters**
This pull request contains the proposed changes to ``devMotorAsyn.c`` from issue #164

### CODE REVIEW

**Comment by motorapp** [comment]
Thanks Mark for providing the example, very helpful.  I agree with the request to change to use asynFloat64SyncIO instead.  I've provided an updated devAsynMotor.c in case it reduces work loads.
[devMotorAsyn.tar.gz](https://github.com/epics-modules/motor/files/4900664/devMotorAsyn.tar.gz)

**Comment by tboegi** [comment]
I took the freedom to extract the code from devMotorAsyn.tar.gz and transform it into a PR:
https://github.com/epics-modules/motor/pull/167

The change for MOTOR_RESOULTION is not part of this PR (that should go into
a different commit anyway)

**Comment by kmpeters** [comment]
> I took the freedom to extract the code from devMotorAsyn.tar.gz and transform it into a PR: #167

This pull request is also an attempt at that.  I haven't had time to make and test the change @MarkRivers suggested.

**Comment by tboegi** [comment]
@kmpeters 
I didn't want to confuse you.
#167 should contain a cleaned up version of devMotorAsyn.c
Feel free to have a look (and use it in this PR or not)

**Comment by kmpeters** [comment]
Merged #167 instead of this pull req.

**Pull request closed without merging**
