### PR TITLE
Add raw limits so that soft limits are synced with motor resolution change 

### LINKED ISSUE #191: user/dial limits: change when motor/encoder resolution changes
Currently the motor record does nothing with dial/user limits when a motor encoder resolution changes. 

this is potentially problematic if a device stores soft limits on the controller (in our case at ISIS/STFC a Galil) which are not scaled (ie in steps), as the motor record does not re-scale these values by calling set_dial_highlimit etc. 

I propose that, when changing the motor/encoder resolution, either: 
- we re-scale the soft limits based on the scaling factor of the motor resolution change, so that an MRES change from 0.05 to 0.1 means a dial low limit of -10 becomes -20 (or the other way round, my maths might be wrong?) - currently we re-scale the VELO, VMAX, BVEL, VBAS and update them according to the new motor resolution, but this is easy because they are all derivative of mres * something else which is not scaled
- we re-send the limits to the device, but scale them using the new resolution. this means the fields stay the same EPICS side but are re-adjusted on the device. 

The former feels like it would require caching the old mres so we can compare against it when trying to rescale the limits.
I think the latter would just be a case of calling set_dial_{high, low}limit() and then set_user_limits from motorRecord.cc

### PR DESCRIPTION
**Pull request by rerpha**
Fixes #191

### CODE REVIEW

**Comment by rerpha** [comment]
hi, was just wondering if you had a chance to review this? Cheers

**Comment by kmpeters** [comment]
I plan to test this soon.  I want to include it in the next motor release.

**Comment by kmpeters** [comment]
I'm testing this pull request with simulated motors.  When I change a dial limit, a camonitor shows the dial limit updates twice (both times with the same value) and the raw limits don't update.

**Comment by kmpeters** [comment]
The double-camonitor-entries-for-the-limit-being-changed behavior is apparently normal behavior that is also present on the master branch.

I see the RHLM and RLLM values change in dbpr output from iocsh, but ca clients only get the correct value at the time they connect.

**Comment by kmpeters** [comment]
Adding these lines fixes the ca-clients-failing-to-update problem:

```diff
diff --git a/motorApp/MotorSrc/motorRecord.cc b/motorApp/MotorSrc/motorRecord.cc
index 77658993..e4a106b8 100644
--- a/motorApp/MotorSrc/motorRecord.cc
+++ b/motorApp/MotorSrc/motorRecord.cc
@@ -3527,6 +3527,10 @@ static void monitor(motorRecord * pmr)
         db_post_events(pmr, &pmr->homf, local_mask);
     if ((local_mask = monitor_mask | (MARKED_AUX(M_HOMR) ? DBE_VAL_LOG : 0)))
         db_post_events(pmr, &pmr->homr, local_mask);
+    if ((local_mask = monitor_mask | (MARKED_AUX(M_RHLM) ? DBE_VAL_LOG : 0)))
+        db_post_events(pmr, &pmr->rhlm, local_mask);
+    if ((local_mask = monitor_mask | (MARKED_AUX(M_RLLM) ? DBE_VAL_LOG : 0)))
+        db_post_events(pmr, &pmr->rllm, local_mask);
```

**Comment by kmpeters** [comment]
Commit 99d0c414157a9dcfcfc90cc196d8155df477ce12 fixed updating RHLM/DLLM when HLM/DHLM/LLM/DHLM change, but not when the resolution changes.

**Comment by kmpeters** [comment]
> Commit [99d0c41](https://github.com/epics-modules/motor/commit/99d0c414157a9dcfcfc90cc196d8155df477ce12) fixed updating RHLM/RLLM when HLM/DHLM/LLM/DHLM change, but not when the resolution changes.

RHLM/RLLM *shouldn't* change when MRES changes.

**Review by kmpeters — APPROVED** [review]

**Pull request merged**
