### PR TITLE
190305 compiler warnings

### PR DESCRIPTION
**Pull request by tboegi**

### CODE REVIEW

**Comment by MarkRivers** [comment]
I have long wanted to greatly reduce the compiler warnings in motor, so I like the idea of this pull request.  It seems to me, however, that it would be better to break this up into a number of smaller requests.  Perhaps that would be easier if we waited until Kevin breaks up motor into individual repositories.

Here are some specific comments on the directories I am mainly responsible for:
- NewportSrc
  - `XPS_C8_drivers.cpp, XPS_C8_drivers.h, XPS_C8_errors.h`.  These are vendor files, that are downloaded from XPS controller and are updated from time to time when the XPS firmware changes.  As such I try to modify them as little as possible to get them to build with the EPICS build system.  While they do generate some compiler warnings, eliminating those means having to re-apply many changes each time we get a new version from the vendor.
  - `drvXPSAsyn.c`  This is an old Model 2 driver and should be deleted.
- AcsSrc:  
  - `devMCB4B.cc,  drvMCB4B.cc.,  drvMCB4B.h`  These are old Model 1 files and should be deleted.

**Comment by kmpeters** [comment]
>  Perhaps that would be easier if we waited until Kevin breaks up motor into individual repositories.

A VxWorks problem has kept me busy for the last few weeks, but we have a workaround for that now.  I plan to begin the work of splitting the motor module next week.

**Comment by kmpeters** [comment]
Keep this open even though it can't be merged.  I don't want to forget to manually apply these changes to the driver modules.

**Comment by tboegi** [comment]
Hej Kevin,
I have applied the patches automatically & manually and the modules look like this:
I can commit all of them, but I can't push to  https://github.com/epics-motor/
Could you give me write access here, please?


       modified:   modules/motorAMCI (modified content)
        modified:   modules/motorAcs (modified content)
        modified:   modules/motorAcsTech80 (modified content)
        modified:   modules/motorAerotech (modified content)
        modified:   modules/motorAttocube (modified content)
        modified:   modules/motorDeltaTau (modified content)
        modified:   modules/motorFaulhaber (modified content)
        modified:   modules/motorIms (modified content)
        modified:   modules/motorKohzu (modified content)
        modified:   modules/motorMXmotor (modified content)
        modified:   modules/motorMclennan (modified content)
        modified:   modules/motorMicos (modified content, untracked content)
        modified:   modules/motorMicroMo (modified content)
        modified:   modules/motorMicronix (modified content)
        modified:   modules/motorNewFocus (modified content)
        modified:   modules/motorNewport (modified content)
        modified:   modules/motorOms (modified content)
        modified:   modules/motorOmsAsyn (modified content)
        modified:   modules/motorOriel (modified content)
        modified:   modules/motorPI (modified content)
        modified:   modules/motorPIGCS2 (modified content)
        modified:   modules/motorParker (modified content)
        modified:   modules/motorPhytron (modified content)
        modified:   modules/motorPiJena (modified content)
        modified:   modules/motorSmarAct (modified content)
        modified:   modules/motorSmartMotor (modified content)
        modified:   modules/motorThorLabs (modified content)

**Comment by kmpeters** [comment]
> Could you give me write access here, please?

@tboegi, I invited you to join the epics-motor organization.  Once you accept the invitation by clicking the link in the email, you should be able to push to the driver repos.

**Comment by tboegi** [comment]
I updated the submodules now with a pull request for each,
with minimal changes only, so more PR may follow later.
As the first step, fix the signature of send_mess() in all of them.
        modified:   modules/motorAcs (new commits)
        modified:   modules/motorAcsTech80 (new commits)
        modified:   modules/motorAerotech (new commits)
        modified:   modules/motorFaulhaber (new commits)
        modified:   modules/motorIms (new commits)
        modified:   modules/motorKohzu (new commits)
        modified:   modules/motorMclennan (new commits)
        modified:   modules/motorMicos (new commits)
        modified:   modules/motorMicroMo (new commits)
        modified:   modules/motorNewFocus (new commits)
        modified:   modules/motorNewport (new commits)
        modified:   modules/motorOms (new commits)
        modified:   modules/motorOriel (new commits)
        modified:   modules/motorPI (new commits)
        modified:   modules/motorParker (new commits)
        modified:   modules/motorPiJena (new commits)
        modified:   modules/motorSmartMotor (new commits)
        modified:   modules/motorThorLabs (new commits)

I would like somebody else to have a look and merge those, once that is done,
I can open another PR to update the motor module to include the new submodule version.

**Comment by kmpeters** [comment]
> I would like somebody else to have a look and merge those, once that is done,
I can open another PR to update the motor module to include the new submodule version.

@tboegi, I merged all of the pull requests except for this one, about which I added a question to the discussion: https://github.com/epics-motor/motorOms/pull/2

**Pull request closed without merging**
