### PR TITLE
CI: Add simple .travis.yml configuration

### PR DESCRIPTION
**Pull request by klauer**
Adds a simple continuous-integration configuration for Travis CI to ensure that PRs build prior to merging.

### CODE REVIEW

**Comment by kmpeters** [comment]
Which version of EPICS base (and other EPICS modules) will be used to test the builds?  Debian isn't used at Argonne so I'm unfamiliar with how current the debian packages are.

**Comment by klauer** [comment]
Admittedly, they are old, from when @mdavidsaver was still at BNL. Package version numbers are [here](http://epics.nsls2.bnl.gov/debian/current.html).

I made the assumption (probably incorrectly) that since epics-modules/asyn used them, the packages would be sufficient ([reference travis.yml](https://github.com/epics-modules/asyn/blob/master/.travis.yml)). 

That said, motor master builds in this version - see my own travis output [here](https://travis-ci.org/klauer/motor/builds/267729250).

**Comment by kmpeters** [comment]
While I think this is a good idea in general, it seems like labeling a build as "passing" if it builds against base-3.14.12.3 on Ubuntu is not necessarily a good idea, since it leaves off many OSes (VxWorks, Windows, OS X) and versions of base (3.15, specifically).

I'm curious to hear the thoughts of @MarkRivers, @prjemian, and @rsluiter.

**Comment by mdavidsaver** [comment]
fyi. for my modules I've been building dependencies from source to more easily test a variety of targets, dependency versions, and other build options.  I've been intending to standardize the associated scripts, but so far it's been copy+paste to various projects.

https://github.com/epics-modules/mrfioc2/blob/master/.travis.yml

https://github.com/mdavidsaver/pvAccessCPP/blob/master/.travis.yml

https://github.com/mdavidsaver/iocStats/blob/master/.travis.yml

https://github.com/epics-base/epics-base/blob/3.16/.travis.yml

I will also note

https://github.com/epics-base/epics-base/blob/3.16/appveyor.yml

**Comment by klauer** [comment]
Thanks @mdavidsaver - I'll shamelessly nab one of those and give it a try for the motor record. Eventually standardizing on a set of scripts for EPICS-related CI builds would be great, for sure.

**Comment by prjemian** [comment]
+1 for the CI support

Remember that CI testing is always limited. This is a start.

@anjohnson, can you comment?

Pete

**Comment by MarkRivers** [comment]
The areaDetector/ADCore Travis CI also only tests on Linux.  The APS Jenkins build server tests on many architectures (Linux 32/64, Windows 32/64 static/dynamic, vxWorks 5.5, 6.9).  

The CI is useful because it runs every time there is a commit to ADCore, not just on a commit to top-level areaDetector which is when Jenkins runs.

It also used to use the Debian packages for asyn and EPICS base.  I changed to building these from source because the Debian packages were based on 3.14.12.3 and that has a bug which prevents it from working on recent versions of ADCore.  I also build EPICS V4 from source.  Build these from source slows things down by 5 minutes or so.  However, Michael shared his recipe for caching builds of dependencies so it will not rebuild them if they have not changed.  I have not implemented that yet, but I plan to in the future.

**Comment by MarkRivers** [comment]
There is a job on the Jenkins build server called [Synapps_3.14](https://jenkins.aps.anl.gov/view/Synapps%203.14/).  

However the motor module does not appear in that job, and other modules like sscan have not run since November 2015.  It would seem like a good idea to get that job running and building all synApps modules.  It seems like it would also be good to enhance that job to build both base 3.14 and 3.15 and to build for Windows and vxWorks.  That will be much more thorough test than the Travis CI.  In particular it should address the problems that are being discussed in [recent issues](https://github.com/epics-modules/motor/issues/67).  These arise because people often fail to build on Windows before they make commits to synApps modules and the problems often do not show up until after a new version of synApps is released.

**Comment by rsluiter** [comment]
Motor module continuous-integration is desirable, but Kevin is trying to address some pull request before releasing a new motor module version. After over 2+1/2 years without a new release, that needs to be a priority.

**Pull request closed without merging**
