### PR TITLE
additional panels used by USAXS

### PR DESCRIPTION
**Pull request by prjemian**
@kmpeters These screens are used by the USAXS.  Created with Qt Designer.

### CODE REVIEW

**Comment by kmpeters** [comment]
The motorApp/op/ui directory currently contains ui files that were auto-converted from adl files.  Should we move the existing, auto-converted ui files to an autoconvert subdirectory of ui before adding ui files that were created in designer?  If not, how will we tell auto-converted ui files from designer-created ui files in the future?

**Comment by prjemian** [comment]
All the other screens in that directory are autoconverted.  I will change this branch into this format:

```
...
motorApp/
  op/
    ui/
      motor#xU.ui
      autoconvert/
        *.ui   <-- all other existing screens will be moved here
```

**Comment by prjemian** [comment]
We should change the caQtDM startup scripts in xxx to look in both directories now

**Comment by timmmooney** [comment]
I did that already.  xxx/start_caQtDM now sources setup_epics_common, which sets display paths for both MEDM and caQtDM, and includes */ui followed by */ui/autoconvert

**Pull request merged**
